"""Zero-to-local bootstrap: install llama.cpp, download right-sized GGUFs,
write tuned launch artifacts, start the server.

Every step is idempotent (already-satisfied work is skipped, so re-running
`kultivait init` converges) and asks before mutating. All process, network,
and filesystem access is injected so tests never touch the real system.
"""

import os
import shutil
import stat
import subprocess
import time
from pathlib import Path

import httpx

from kultivait.hardware import SetupPlan

BREW_INSTALL_HINT = (
    "Homebrew is required to install llama.cpp automatically.\n"
    "Install it first:\n"
    '  /bin/bash -c "$(curl -fsSL '
    'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"\n'
)


def ask(prompt: str, input_fn=input) -> bool:
    """[Y/n] confirm, default yes — every step was already offered explicitly."""
    return input_fn(f"{prompt} [Y/n] ").strip().lower() in ("", "y", "yes")


def models_dir() -> Path:
    """Same GGUF cache llama-server uses and cli._gguf_dirs() scans."""
    override = os.environ.get("KULTIVAIT_LLAMACPP_MODELS_DIR") or os.environ.get(
        "LLAMA_CACHE"
    )
    if override:
        return Path(override)
    return Path.home() / "Library" / "Caches" / "llama.cpp"


def ensure_llamacpp(confirm=ask, run_cmd=subprocess.run, which=shutil.which) -> str:
    """Idempotent install step: "present" | "advisory" | "declined" |
    "installed" | "failed"."""
    if which("llama-server"):
        return "present"
    if not which("brew"):
        print(BREW_INSTALL_HINT)
        return "advisory"
    if not confirm("Install llama.cpp via Homebrew (brew install llama.cpp)?"):
        return "declined"
    result = run_cmd(["brew", "install", "llama.cpp"])
    return "installed" if result.returncode == 0 else "failed"


CHUNK = 1 << 20


def _download(client, url: str, dest: Path, expected_bytes: int, log=print) -> None:
    """Stream to <dest>.part, resume via Range, rename when complete."""
    if dest.exists() and dest.stat().st_size == expected_bytes:
        log(f"  {dest.name}: already present")
        return
    part = dest.with_name(dest.name + ".part")
    headers, mode = {}, "wb"
    if part.exists():
        headers["Range"] = f"bytes={part.stat().st_size}-"
        mode = "ab"
    with client.stream("GET", url, headers=headers, follow_redirects=True) as r:
        if r.status_code == 200 and mode == "ab":
            mode = "wb"  # server ignored Range: start over rather than duplicate
        r.raise_for_status()
        done = part.stat().st_size if mode == "ab" else 0
        with open(part, mode) as f:
            for chunk in r.iter_bytes(CHUNK):
                f.write(chunk)
                done += len(chunk)
                log(
                    f"\r  {dest.name}: {done / 2**20:.0f}/{expected_bytes / 2**20:.0f} MB",
                    end="",
                )
        log("")
    part.rename(dest)


def download_models(
    plan: SetupPlan,
    dest: Path,
    confirm=ask,
    client: "httpx.Client | None" = None,
    log=print,
) -> bool:
    """Confirm once (sizes shown), then fetch whatever isn't already on disk."""
    todo = [
        m
        for m in plan.models
        if not (dest / m.filename).exists()
        or (dest / m.filename).stat().st_size != m.approx_bytes
    ]
    if not todo:
        return True
    log("models to download:")
    for m in todo:
        log(f"  {m.filename}  ({m.approx_bytes / 2**30:.1f} GB)")
    total_gb = sum(m.approx_bytes for m in todo) / 2**30
    if not confirm(f"Download {total_gb:.1f} GB into {dest}?"):
        return False
    dest.mkdir(parents=True, exist_ok=True)
    client = client or httpx.Client(timeout=60)
    for m in todo:
        _download(client, m.url(), dest / m.filename, m.approx_bytes, log=log)
    return True


def write_artifacts(
    plan: SetupPlan, kultivait_home: Path, gguf_dir: Path
) -> "tuple[Path, Path]":
    """Presets INI + start script, regenerated from the plan every run —
    like config.toml, these are decisions made visible, not precious state."""
    kultivait_home.mkdir(parents=True, exist_ok=True)
    embed = next(m for m in plan.models if m.role == "embed")
    preset = kultivait_home / "llamacpp-presets.ini"
    preset.write_text(
        "# generated by kultivait init — regenerate by re-running it\n"
        f"[{embed.filename.removesuffix('.gguf')}]\n"
        f"model = {gguf_dir / embed.filename}\n"
        "embedding = 1\n"
    )
    script = kultivait_home / "start-llamacpp.sh"
    log_path = kultivait_home / "llamacpp.log"
    sysctl_comment = ""
    if plan.wired_limit_mb:
        sysctl_comment = (
            "# Optional: raise the GPU memory cap from "
            f"~{plan.default_gpu_cap_mb} MB (resets on reboot):\n"
            f"#   sudo sysctl iogpu.wired_limit_mb={plan.wired_limit_mb}\n"
        )
    script.write_text(
        "#!/bin/sh\n"
        "# generated by kultivait init — regenerate by re-running it\n"
        f"{sysctl_comment}"
        f'exec llama-server --models-dir "{gguf_dir}" --models-preset "{preset}" \\\n'
        f"  {' '.join(plan.server_flags)} \\\n"
        f'  >> "{log_path}" 2>&1\n'
    )
    script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return preset, script
