#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# herdr-kultivat-ops: seats the kultivait herd in Herdr (arch on opencode/GLM-5.3,
# agy-docs + agy-gh on agy/gemini-flash, services + ops panes), then kicks
# off the next wayfinder round. Re-run for each new round: finished stages
# are detected and skipped.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "herdr × kultivait — seat the herd, start the round"

REPO="Standard-Pentest/kultivait"

# split_pane PANE_ID DIRECTION → new pane id (sibling split, cwd preserved,
# user's focus untouched). Panes start at a shell prompt, ready for agents.
split_pane() {
  herdr pane split --pane "$1" --direction "$2" --cwd "$PWD" --no-focus \
    | jq -r '.result.pane.pane_id'
}

# agent_alive NAME → true if a live agent with that name exists.
agent_alive() {
  herdr agent list 2>/dev/null | grep -q "\"$1\""
}

# seat_agent NAME PANE KINDVAR [native agent args...] starts an agent,
# treating herdr's own validation as the authority on kinds: a rejected kind
# re-prompts (up to 3 attempts) and a corrected kind is persisted to ENV_FILE.
# Returns 2 for agent_not_ready (the kind was fine; the agent needs attention).
seat_agent() {
  local name="$1" pane="$2" kindvar="$3" attempt out reply
  shift 3
  for attempt in 1 2 3; do
    if out=$(herdr agent start "$name" --kind "${!kindvar}" --pane "$pane" -- "$@" 2>&1); then
      if (( attempt > 1 )); then write_env "$kindvar" "${!kindvar}"; fi
      return 0
    fi
    printf '%s\n' "$out" | sed 's/^/  /'
    if grep -q "agent_not_ready" <<<"$out"; then
      return 2
    fi
    warn "herdr rejected --kind '${!kindvar}' for ${name} (attempt ${attempt}/3)"
    if [[ -n "${KINDS_TXT:-}" ]]; then
      say "kinds this herdr installation recognizes:"
      printf '%s\n' "$KINDS_TXT" | sed 's/^/  /'
    fi
    printf '  %sInteractive kind for %s: %s' "$BOLD" "$name" "$RESET"
    read -r reply || true
    [[ -z "$reply" ]] && return 1
    printf -v "$kindvar" '%s' "$reply"
  done
  return 1
}

# resume_pane → new pane id off the wizard's own pane, alternating direction
# (used when re-seating a partially built herd, where the original layout
# anchors are gone).
RESUME_DIR=right
resume_pane() {
  local d="$RESUME_DIR"
  if [[ "$RESUME_DIR" = right ]]; then RESUME_DIR=down; else RESUME_DIR=right; fi
  split_pane "$HERDR_PANE_ID" "$d"
}

# detect_kind CANDIDATE... → first candidate appearing as a word in the
# installed `herdr agent` kind list.
detect_kind() {
  local c
  for c in "$@"; do
    if grep -qiE "(^|[^a-z])${c}([^a-z]|$)" <<<"$KINDS_TXT"; then
      printf '%s' "$c"; return 0
    fi
  done
  return 1
}

# ── Stage 1/7 · Preflight ─────────────────────────────────────────────────
stage "Preflight: Herdr, repo, runtime"
if [[ "${HERDR_ENV:-}" != 1 ]]; then
  warn "not running inside a Herdr-managed pane (HERDR_ENV != 1)."
  say  "Re-run this script from a pane inside your kultivait Herdr workspace;"
  say  "the herdr skill forbids driving Herdr from outside it."
  exit 1
fi
command -v herdr >/dev/null 2>&1 || { warn "herdr not on PATH"; exit 1; }
command -v jq   >/dev/null 2>&1 || { warn "jq not on PATH"; exit 1; }
command -v gh   >/dev/null 2>&1 || { warn "gh not on PATH (needed for wayfinder rounds)"; exit 1; }
[[ -f pyproject.toml && -d src/kultivait ]] || { warn "run from the kultivait repo root"; exit 1; }
note "this pane: ${HERDR_WORKSPACE_ID:-?} / ${HERDR_TAB_ID:-?} / ${HERDR_PANE_ID:-?}"

if curl -sf --max-time 3 http://localhost:11434/api/tags >/dev/null 2>&1; then
  note "ollama is up (:11434) — the local post-processor tier is available"
else
  warn "ollama is not answering on :11434"
  if confirm "start it now with 'brew services start ollama'?"; then
    brew services start ollama
    for _ in $(seq 1 15); do
      curl -sf --max-time 2 http://localhost:11434/api/tags >/dev/null 2>&1 && break
      sleep 2
    done
    if curl -sf --max-time 2 http://localhost:11434/api/tags >/dev/null 2>&1; then
      note "ollama is up"
    else
      warn "ollama still down; stage 6 (kultivait serve) will fail until it runs"
    fi
  fi
fi
if curl -sf --max-time 2 http://localhost:8080/v1/models >/dev/null 2>&1; then
  warn "llama.cpp also appears up on :8080 — ollama wins detection, but these"
  warn "runtimes must never both serve the herd; stop one before continuing"
  pause
fi
pause

# ── Stage 2/7 · Survey the herd & pick agent kinds ────────────────────────
stage "Survey the herd & pick agent kinds"
say "live agents right now:"
herdr agent list 2>/dev/null | sed 's/^/  /' || true
KINDS_TXT=$(herdr agent 2>&1 || true)
say "kinds this herdr installation recognizes:"
printf '%s\n' "$KINDS_TXT" | sed 's/^/  /'
DEF_ARCH=$(detect_kind opencode || true)
DEF_AGY=$(detect_kind agy antigravity || true)
note "detected candidates: opencode='${DEF_ARCH:-none}' agy='${DEF_AGY:-none}'"
ask ARCH_KIND "Kind name for the architect (opencode):"
[[ -z "${ARCH_KIND:-}" && -n "$DEF_ARCH" ]] && ARCH_KIND="$DEF_ARCH"
[[ -n "${ARCH_KIND:-}" ]] || { warn "no opencode kind chosen — pick one from the list above"; exit 1; }
ask AGY_KIND "Interactive kind for the agy agents (e.g. agy):"
[[ -z "${AGY_KIND:-}" && -n "$DEF_AGY" ]] && AGY_KIND="$DEF_AGY"
[[ -n "${AGY_KIND:-}" ]] || { warn "no agy kind chosen — pick one from the list above"; exit 1; }
if [[ "${AGY_KIND}" == worker--* ]]; then
  warn "worker--* entries are non-interactive worker kinds — 'agent start' rejects them"
  if ! confirm "keep '${AGY_KIND}' anyway?"; then
    ask AGY_KIND "Interactive kind for the agy agents:"
    [[ -n "${AGY_KIND:-}" ]] || { warn "no agy kind chosen"; exit 1; }
  fi
fi
write_env ARCH_KIND "$ARCH_KIND"
write_env AGY_KIND "$AGY_KIND"

# ── Stage 3/7 · Architect model ───────────────────────────────────────────
stage "Architect model (opencode + szai GLM-5.3)"
OC_AUTH="${HOME}/.local/share/opencode/auth.json"
if [[ -f "$OC_AUTH" ]]; then
  note "providers authenticated to opencode (~/.local/share/opencode/auth.json):"
  jq -r 'keys[] | select(. != "active")' "$OC_AUTH" 2>/dev/null | sed 's/^/    /' || true
else
  warn "opencode has no auth.json — run 'opencode auth login' for your GLM-5.3 provider first"
fi
ask ARCH_MODEL "Model as provider/model (e.g. zai/glm-5.3):"
write_env ARCH_MODEL "$ARCH_MODEL"
# drop keys left by the pi-based predecessor of this stage, if an old run wrote them
if grep -qE '^(PI_KIND|PI_PROVIDER|PI_MODEL)=' "$ENV_FILE" 2>/dev/null; then
  _tmp=$(mktemp)
  grep -vE '^(PI_KIND|PI_PROVIDER|PI_MODEL)=' "$ENV_FILE" > "$_tmp" || true
  mv "$_tmp" "$ENV_FILE"
  note "removed stale PI_* values from the pi-based version"
fi
note "arch will start as: ${ARCH_KIND} --model ${ARCH_MODEL}"
pause

# ── Stage 4/7 · Build the pane layout ─────────────────────────────────────
stage "Build the pane layout"
if agent_alive arch && agent_alive agy-docs && agent_alive agy-gh; then
  note "arch, agy-docs, agy-gh already live — skipping pane creation"
else
  say "this pane's geometry:"
  herdr pane layout --pane "$HERDR_PANE_ID" 2>/dev/null | sed 's/^/  /' || true
  RESUME=0
  for a in arch agy-docs agy-gh; do agent_alive "$a" && RESUME=1; done
  if [[ $RESUME -eq 1 ]]; then
    note "partial herd detected — creating panes only for agents that are absent"
    if ! agent_alive arch; then
      ARCH_PANE=$(resume_pane) || { warn "pane split failed"; exit 1; }
      note "pane for arch: $ARCH_PANE"
    fi
    if ! agent_alive agy-docs; then
      DOCS_PANE=$(resume_pane) || { warn "pane split failed"; exit 1; }
      note "pane for agy-docs: $DOCS_PANE"
    fi
    if ! agent_alive agy-gh; then
      GH_PANE=$(resume_pane) || { warn "pane split failed"; exit 1; }
      note "pane for agy-gh: $GH_PANE"
    fi
  else
    DIR_MAIN=right; DIR_STACK=down
    if ! confirm "split ${DIR_MAIN} off this pane and stack workers ${DIR_STACK}?"; then
      DIR_MAIN=down; DIR_STACK=right
    fi
    ARCH_PANE=$(split_pane "$HERDR_PANE_ID" "$DIR_MAIN") || { warn "pane split failed"; exit 1; }
    DOCS_PANE=$(split_pane "$ARCH_PANE" "$DIR_STACK")    || { warn "pane split failed"; exit 1; }
    GH_PANE=$(split_pane  "$DOCS_PANE" "$DIR_STACK")     || { warn "pane split failed"; exit 1; }
    SRV_PANE=$(split_pane "$HERDR_PANE_ID" "$DIR_STACK") || { warn "pane split failed"; exit 1; }
    OPS_PANE=$(split_pane "$SRV_PANE" "$DIR_MAIN")       || { warn "pane split failed"; exit 1; }
    note "panes: arch=$ARCH_PANE agy-docs=$DOCS_PANE agy-gh=$GH_PANE srv=$SRV_PANE ops=$OPS_PANE"
  fi
fi
pause

# ── Stage 5/7 · Seat the agents ───────────────────────────────────────────
stage "Seat the agents"
if agent_alive arch && agent_alive agy-docs && agent_alive agy-gh; then
  note "all three agents already live — nothing to seat"
else
  if agent_alive arch; then
    note "arch already live — skipping"
  else
    say "starting architect: arch (${ARCH_KIND}, ${ARCH_MODEL})"
    if ! seat_agent arch "$ARCH_PANE" ARCH_KIND --model "$ARCH_MODEL"; then
      warn "arch not seated — inspect: herdr agent read arch  ·  herdr agent get arch"
      pause "settle it, then continue (Ctrl-C to abort)"
    fi
  fi
  if agent_alive agy-docs; then
    note "agy-docs already live — skipping"
  else
    if ! seat_agent agy-docs "$DOCS_PANE" AGY_KIND; then
      warn "agy-docs not seated — inspect: herdr agent read agy-docs"
      pause
    fi
  fi
  if agent_alive agy-gh; then
    note "agy-gh already live — skipping"
  else
    if ! seat_agent agy-gh "$GH_PANE" AGY_KIND; then
      warn "agy-gh not seated — inspect: herdr agent read agy-gh"
      pause
    fi
  fi
  for a in arch agy-docs agy-gh; do
    herdr agent wait "$a" --timeout 60000 >/dev/null 2>&1 \
      || warn "$a still settling — check: herdr agent get $a"
  done
fi
note "herd: arch (architect) · agy-docs (documentation) · agy-gh (github/CI)"
pause

# ── Stage 6/7 · Services ──────────────────────────────────────────────────
stage "Services: kultivait serve on :4114"
if curl -sf --max-time 3 http://localhost:4114/v1/models >/dev/null 2>&1; then
  note "proxy already serving on :4114"
else
  ask SERVE_MATCH "Substring serve prints when ready:"
  [[ -z "${SERVE_MATCH:-}" ]] && SERVE_MATCH="4114"
  write_env SERVE_MATCH "$SERVE_MATCH"
  if [[ -z "${SRV_PANE:-}" ]]; then
    SRV_PANE=$(split_pane "$HERDR_PANE_ID" down) || { warn "pane split failed"; exit 1; }
    note "created a fresh serve pane: $SRV_PANE"
  fi
  herdr pane run "$SRV_PANE" "uv run kultivait serve"
  if ! herdr pane wait-output "$SRV_PANE" --match "$SERVE_MATCH" --timeout 600000; then
    warn "no '${SERVE_MATCH}' seen yet — inspect: herdr pane read $SRV_PANE"
  fi
  if curl -sf --max-time 3 http://localhost:4114/v1/models >/dev/null 2>&1; then
    note "proxy healthy"
  else
    warn "proxy not answering on :4114 yet — arch can still plan; fix before delegating"
  fi
fi
pause

# ── Stage 7/7 · Kick off the next round ───────────────────────────────────
stage "Kick off the next round"
if [[ "${1:-}" == "--loop" ]]; then KULTIVAIT_LOOP=1; fi

# fresh_issues → one "#num  title" line per open issue nobody has touched:
# zero comments and no assignees, lowest number first. Commenting, closing,
# or assigning (our claim) retires an issue from this list — that retirement
# is what lets the loop make progress instead of spinning.
fresh_issues() {
  gh issue list -R "$REPO" --state open --json number,title,comments,assignees \
    --jq 'map(select(((.comments // []) | length) == 0 and ((.assignees // []) | length) == 0))
          | sort_by(.number) | .[] | "#\(.number)  \(.title)"'
}

# arch_brief NUM TITLE → the full architect brief for one ticket.
arch_brief() {
  cat <<'EOF'
You are the ARCHITECT of the kultivait herd, running inside a Herdr-managed
pane — the herdr CLI on PATH drives your coworkers. Live workers:
  agy-docs — documentation, ADRs, README, landing copy
  agy-gh   — GitHub issues/PRs/triage/CI via gh (upstream: Standard-Pentest/kultivait)
The kultivait routing proxy serves on :4114.

Run the development loop for the ticket below:
1. Read AGENTS.md, CONTEXT.md, and docs/adr/ first; use the glossary vocabulary.
2. Spec the ticket as the repo's mandatory 3-line preamble (AGENTS.md):
   Intended Outcome / Explicit Done-Criteria / Verification Step.
3. Delegate: herdr agent prompt <worker> "<brief>; write your complete
   response to /tmp/<worker>-out.md and reply with only the path" --wait
   Choose agy-docs for docs work, agy-gh for github/CI work. If a worker
   returns blocked, a dialog needs the human: surface it with
   'herdr agent read <worker>' — never answer dialogs yourself.
4. Post-process locally: uv run kultivait prune --from execute --to report
   /tmp/<worker>-out.md  (check 'kultivait prune --help' for exact phases).
5. Verify: uv run pytest -q for code tickets. Send failures back to the
   worker as a follow-up prompt; do not fix them in your own editor.
6. Resolve: comment the distilled result on the issue, close it, append a
   pointer to the wayfinder map's Decisions-so-far (docs/agents/issue-tracker.md).
7. Bookkeep: append a per-task ledger record per TODO-AGY.md §3 (worker,
   duration, test_passed, costs), then report 'uv run kultivait harvest'.
EOF
  printf '\n\nStart now with ticket #%s: %s\n' "$1" "$2"
}

# hand_off NUM → claim the ticket, brief arch, block until arch settles.
# Returns 0 = settled idle/done (the brief's comment/close retires the
# issue), 1 = brief not delivered, 2 = arch ended blocked (a human must
# answer its dialog before any further rounds).
hand_off() {
  local num="$1" title state
  title=$(gh issue view "$num" -R "$REPO" --json title --jq .title)
  if gh issue edit "$num" -R "$REPO" --add-assignee "@me" >/dev/null; then
    note "claimed #${num}: ${title}"
  else
    warn "claim failed — assign yourself on the issue, arch proceeds regardless"
  fi
  if ! herdr agent prompt arch "$(arch_brief "$num" "$title")" --wait; then
    warn "could not prompt arch — if it is waiting on a dialog, answer it, then re-run:"
    say  "herdr agent read arch --source recent-unwrapped --lines 120"
    say  "herdr agent prompt arch \"<brief for #${num}>\""
    return 1
  fi
  state=$(herdr agent get arch | jq -r '.result.agent.agent_status' 2>/dev/null) || state=unknown
  if [[ "$state" == "blocked" ]]; then
    warn "arch is blocked on a dialog only the human can answer:"
    say  "herdr agent read arch --source recent-unwrapped --lines 120"
    return 2
  fi
  note "arch settled (${state}) on #${num}"
  return 0
}

if [[ "${KULTIVAIT_LOOP:-}" = 1 ]]; then
  note "loop mode: draining every open, uncommented, unassigned issue"
  while :; do
    if ! QUEUE=$(fresh_issues); then
      warn "gh issue list failed — stopping the loop"
      SKIPPED+=("loop stopped: gh issue list failed")
      break
    fi
    if [[ -z "$QUEUE" ]]; then
      note "queue dry — no open issues without comments (or assignees) remain"
      break
    fi
    say "fresh queue ($(wc -l <<<"$QUEUE" | tr -d ' ') left):"
    printf '  %s\n' "$QUEUE"
    NEXT="${QUEUE%%$'\n'*}"
    NUM="${NEXT%% *}"; NUM="${NUM#\#}"
    rc=0; hand_off "$NUM" || rc=$?
    if (( rc == 2 )); then
      SKIPPED+=("loop stopped: arch blocked on #${NUM}")
      break
    elif (( rc != 0 )); then
      SKIPPED+=("loop stopped: brief delivery failed on #${NUM}")
      break
    fi
    # settled ≠ acted: if the issue is still open with zero comments, arch's
    # round changed nothing — surface it instead of requeueing it forever
    if [[ -n "$(gh issue view "$NUM" -R "$REPO" --json number,state,comments \
        --jq 'select((.state | ascii_downcase) == "open" and ((.comments // []) | length) == 0) | .number' 2>/dev/null)" ]]; then
      warn "#${NUM} survived its arch round unchanged — inspect before looping again"
      SKIPPED+=("loop stopped: #${NUM} unchanged after an arch round")
      break
    fi
    note "#${NUM} retired — pulling the next fresh issue"
  done
else
  say "open, unassigned & uncommented issues on ${REPO}:"
  QUEUE=$(fresh_issues || true)
  if [[ -z "$QUEUE" ]]; then
    warn "no fresh open issues — create one, then re-run this script"
    SKIPPED+=("round kickoff: no fresh issue to claim")
  else
    printf '  %s\n' "$QUEUE"
    ask TICKET "Issue number to claim and hand to arch (Enter = skip):"
  fi
  if [[ -n "${TICKET:-}" ]]; then
    hand_off "$TICKET" || true
  fi
fi

SKIPPED+=("worktree isolation for parallel file-editing workers — explore: herdr worktree")

finish
note "one round:   scripts/herdr-kultivat-ops.sh             (pick a ticket by hand)"
note "drain queue: KULTIVAIT_LOOP=1 scripts/herdr-kultivat-ops.sh   (or pass --loop)"
note "finished stages skip themselves; only stage 7 runs again."
