#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# herdr-kultivait-session: recreates the kultivait herd experience in Herdr —
# looper (agy) as the main pane, arch (opencode/GLM-5.3), agy-docs, agy-gh,
# kultivait serve on :4114, and the /tmp/herdr-process.log tail pane — then
# kicks off the session by mode: wayfinder charter, brainstorm, or resume of
# an existing map. Supersedes herdr-kultivat-ops.sh. Re-run any time:
# finished stages detect themselves and skip.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "herdr × kultivait — seat the herd, pick the mode, kick the loop"

REPO="Standard-Pentest/kultivait"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BRIEFS="$SCRIPT_DIR/herdr-briefs"
LOG_FILE="/tmp/herdr-process.log"

# split_pane PANE_ID DIRECTION → new pane id (sibling split, cwd preserved,
# user's focus untouched). Panes start at a shell prompt, ready for agents.
split_pane() {
  herdr pane split --pane "$1" --direction "$2" --cwd "$PWD" --no-focus \
    | jq -r '.result.pane.pane_id'
}

# agent_alive NAME → true if a live agent with that name exists.
agent_alive() {
  herdr agent list 2>/dev/null | grep -q "\"$1\""
}

# seat_agent NAME PANE KINDVAR [native agent args...] starts an agent,
# treating herdr's own validation as the authority on kinds: a rejected kind
# re-prompts (up to 3 attempts) and a corrected kind is persisted to ENV_FILE.
# Returns 2 for agent_not_ready (the kind was fine; the agent needs attention).
seat_agent() {
  local name="$1" pane="$2" kindvar="$3" attempt out reply
  shift 3
  for attempt in 1 2 3; do
    if out=$(herdr agent start "$name" --kind "${!kindvar}" --pane "$pane" -- "$@" 2>&1); then
      if (( attempt > 1 )); then write_env "$kindvar" "${!kindvar}"; fi
      return 0
    fi
    printf '%s\n' "$out" | sed 's/^/  /'
    if grep -q "agent_not_ready" <<<"$out"; then
      return 2
    fi
    warn "herdr rejected --kind '${!kindvar}' for ${name} (attempt ${attempt}/3)"
    if [[ -n "${KINDS_TXT:-}" ]]; then
      say "kinds this herdr installation recognizes:"
      printf '%s\n' "$KINDS_TXT" | sed 's/^/  /'
    fi
    printf '  %sInteractive kind for %s: %s' "$BOLD" "$name" "$RESET"
    read -r reply || true
    [[ -z "$reply" ]] && return 1
    printf -v "$kindvar" '%s' "$reply"
  done
  return 1
}

# seat_brief NAME FILE sends a standing brief to a seated agent and waits for
# it to settle. Missing file is a warning, never a dead end.
seat_brief() {
  local name="$1" file="$2"
  if [[ ! -f "$file" ]]; then
    warn "brief not found: $file — ${name} runs without its standing brief"
    SKIPPED+=("seat brief for ${name} ($file missing)")
    return 0
  fi
  herdr agent prompt "$name" "$(cat "$file")" >/dev/null 2>&1 || {
    warn "could not send ${name}'s seat brief — send it later:"
    say  "herdr agent prompt ${name} \"\$(cat ${file})\""
    SKIPPED+=("seat brief delivery for ${name}")
    return 0
  }
  herdr agent wait "$name" --timeout 120000 >/dev/null 2>&1 \
    || warn "${name} still absorbing its brief — check: herdr agent get ${name}"
  note "${name} seated with brief: $(basename "$file")"
}

# resume_pane → new pane id off the wizard's own pane, alternating direction
# (used when re-seating a partially built herd, where the original layout
# anchors are gone).
RESUME_DIR=right
resume_pane() {
  local d="$RESUME_DIR"
  if [[ "$RESUME_DIR" = right ]]; then RESUME_DIR=down; else RESUME_DIR=right; fi
  split_pane "$HERDR_PANE_ID" "$d"
}

# detect_kind CANDIDATE... → first candidate appearing as a word in the
# installed `herdr agent` kind list.
detect_kind() {
  local c
  for c in "$@"; do
    if grep -qiE "(^|[^a-z])${c}([^a-z]|$)" <<<"$KINDS_TXT"; then
      printf '%s' "$c"; return 0
    fi
  done
  return 1
}

# log_pane → pane id of the existing process-log tail pane, if any.
log_pane() {
  herdr pane list --workspace "${HERDR_WORKSPACE_ID:-}" 2>/dev/null \
    | jq -r '.result.panes[]? | select((.terminal_title // "") | test("herdr-process[.]log")) | .pane_id' \
    | head -n1
}

# newest_map → "#N  title" of the newest open wayfinder:map issue (empty if none).
newest_map() {
  gh issue list -R "$REPO" --label wayfinder:map --state open \
    --json number,title --jq 'sort_by(.number) | reverse | (.[0] // empty) | "#\(.number)  \(.title)"'
}

# kick_looper TEXT sends the kickoff to the looper and hands the human the pane.
kick_looper() {
  if herdr agent prompt looper "$1" >/dev/null 2>&1; then
    herdr agent focus looper >/dev/null 2>&1 || true
    note "looper kicked — focus moved to the looper pane; it reports there when done"
  else
    warn "could not prompt looper — paste this into its pane yourself:"
    printf '  %s\n' "$1"
    SKIPPED+=("looper kickoff (deliver by hand)")
  fi
}

# ── Stage 1/8 · Preflight ─────────────────────────────────────────────────
stage "Preflight: Herdr, repo, runtime"
if [[ "${HERDR_ENV:-}" != 1 ]]; then
  warn "not running inside a Herdr-managed pane (HERDR_ENV != 1)."
  say  "Re-run this script from a pane inside your kultivait Herdr workspace;"
  say  "the herdr skill forbids driving Herdr from outside it."
  exit 1
fi
command -v herdr >/dev/null 2>&1 || { warn "herdr not on PATH"; exit 1; }
command -v jq   >/dev/null 2>&1 || { warn "jq not on PATH"; exit 1; }
command -v gh   >/dev/null 2>&1 || { warn "gh not on PATH (needed for wayfinder maps)"; exit 1; }
[[ -f pyproject.toml && -d src/kultivait ]] || { warn "run from the kultivait repo root"; exit 1; }
[[ -d "$BRIEFS" ]] || { warn "briefs directory missing: $BRIEFS"; exit 1; }
gh auth status >/dev/null 2>&1 || { warn "gh not authenticated — run 'gh auth login' first"; exit 1; }
note "this pane: ${HERDR_WORKSPACE_ID:-?} / ${HERDR_TAB_ID:-?} / ${HERDR_PANE_ID:-?}"

if curl -sf --max-time 3 http://localhost:11434/api/tags >/dev/null 2>&1; then
  note "ollama is up (:11434) — the local tiers are available"
else
  warn "ollama is not answering on :11434"
  if confirm "start it now with 'brew services start ollama'?"; then
    brew services start ollama
    for _ in $(seq 1 15); do
      curl -sf --max-time 2 http://localhost:11434/api/tags >/dev/null 2>&1 && break
      sleep 2
    done
    if curl -sf --max-time 2 http://localhost:11434/api/tags >/dev/null 2>&1; then
      note "ollama is up"
    else
      warn "ollama still down; stage 7 (kultivait serve) will limp until it runs"
    fi
  fi
fi
if curl -sf --max-time 2 http://localhost:8080/v1/models >/dev/null 2>&1; then
  warn "llama.cpp also appears up on :8080 — ollama wins detection, but these"
  warn "runtimes must never both serve the herd; stop one before continuing"
  pause
fi
pause

# ── Stage 2/8 · Survey the herd & pick agent kinds ────────────────────────
stage "Survey the herd & pick agent kinds"
say "live agents right now:"
herdr agent list 2>/dev/null | sed 's/^/  /' || true
KINDS_TXT=$(herdr agent 2>&1 || true)
say "kinds this herdr installation recognizes:"
printf '%s\n' "$KINDS_TXT" | sed 's/^/  /'
DEF_ARCH=$(detect_kind opencode || true)
DEF_AGY=$(detect_kind agy antigravity || true)
note "detected candidates: opencode='${DEF_ARCH:-none}' agy='${DEF_AGY:-none}'"
ask ARCH_KIND "Kind name for the architect (opencode):"
[[ -z "${ARCH_KIND:-}" && -n "$DEF_ARCH" ]] && ARCH_KIND="$DEF_ARCH"
[[ -n "${ARCH_KIND:-}" ]] || { warn "no opencode kind chosen — pick one from the list above"; exit 1; }
ask AGY_KIND "Interactive kind for the agy agents (looper, agy-docs, agy-gh):"
[[ -z "${AGY_KIND:-}" && -n "$DEF_AGY" ]] && AGY_KIND="$DEF_AGY"
[[ -n "${AGY_KIND:-}" ]] || { warn "no agy kind chosen — pick one from the list above"; exit 1; }
if [[ "${AGY_KIND}" == worker--* ]]; then
  warn "worker--* entries are non-interactive worker kinds — 'agent start' rejects them"
  if ! confirm "keep '${AGY_KIND}' anyway?"; then
    ask AGY_KIND "Interactive kind for the agy agents:"
    [[ -n "${AGY_KIND:-}" ]] || { warn "no agy kind chosen"; exit 1; }
  fi
fi
write_env ARCH_KIND "$ARCH_KIND"
write_env AGY_KIND "$AGY_KIND"

# ── Stage 3/8 · Architect model ───────────────────────────────────────────
stage "Architect model (opencode + szai GLM-5.3)"
OC_AUTH="${HOME}/.local/share/opencode/auth.json"
if [[ -f "$OC_AUTH" ]]; then
  note "providers authenticated to opencode (~/.local/share/opencode/auth.json):"
  jq -r 'keys[] | select(. != "active")' "$OC_AUTH" 2>/dev/null | sed 's/^/    /' || true
else
  warn "opencode has no auth.json — run 'opencode auth login' for your GLM-5.3 provider first"
fi
ask ARCH_MODEL "Model as provider/model:"
[[ -z "${ARCH_MODEL:-}" ]] && ARCH_MODEL="zai/glm-5.3"
write_env ARCH_MODEL "$ARCH_MODEL"
# drop keys left by the pi-based predecessor of this stage, if an old run wrote them
if grep -qE '^(PI_KIND|PI_PROVIDER|PI_MODEL)=' "$ENV_FILE" 2>/dev/null; then
  _tmp=$(mktemp)
  grep -vE '^(PI_KIND|PI_PROVIDER|PI_MODEL)=' "$ENV_FILE" > "$_tmp" || true
  mv "$_tmp" "$ENV_FILE"
  note "removed stale PI_* values from the pi-based version"
fi
note "arch will start as: ${ARCH_KIND} --model ${ARCH_MODEL}"
pause

# ── Stage 4/8 · Session mode ──────────────────────────────────────────────
stage "Pick this session's mode"
say "  w — wayfinder: chart a NEW milestone map with arch (you grill, live, in arch's pane)"
say "  b — brainstorm: direction → design → PRD → tickets with arch (grill-with-docs, live)"
say "  r — resume: kick the looper onto an existing map and let the herd run"
say "  s — seat-only: build the herd, no kickoff"
MODE=""
until [[ "${MODE:-}" =~ ^[wbrs]$ ]]; do
  ask MODE "Mode for this session (w/b/r/s):"
  MODE=$(printf '%s' "${MODE:-}" | tr '[:upper:]' '[:lower:]')
done
write_env LAST_MODE "$MODE"
MILESTONE=""
MAP_NUM=""
case "$MODE" in
  w|b)
    ask MILESTONE "One-liner: the milestone / direction for this session"
    [[ -z "${MILESTONE:-}" ]] && { warn "a charter needs a direction — re-run and give one"; exit 1; }
    ;;
  r)
    NEWEST=$(newest_map || true)
    if [[ -n "$NEWEST" ]]; then
      note "newest open map: $NEWEST"
      DEFAULT_NUM="${NEWEST%% *}"; DEFAULT_NUM="${DEFAULT_NUM#\#}"
    else
      warn "no open wayfinder:map issues found"
      DEFAULT_NUM=""
    fi
    ask MAP_NUM "Map issue number to resume${DEFAULT_NUM:+ (Enter = ${DEFAULT_NUM})}:"
    [[ -z "${MAP_NUM:-}" && -n "$DEFAULT_NUM" ]] && MAP_NUM="$DEFAULT_NUM"
    [[ -n "${MAP_NUM:-}" ]] || { warn "resume needs a map number — re-run and give one"; exit 1; }
    ;;
esac
pause

# ── Stage 5/8 · Build the pane layout + process log ───────────────────────
stage "Build the pane layout + process log"
# fresh session log: truncate, then stamp a session header the tail pane shows
: > "$LOG_FILE"
{
  printf '[SESSION] %s — mode=%s' "$(date '+%Y-%m-%d %H:%M:%S %Z')" "$MODE"
  [[ -n "${MAP_NUM:-}"    ]] && printf ' map=#%s'    "${MAP_NUM}"
  [[ -n "${MILESTONE:-}"  ]] && printf ' milestone="%s"' "${MILESTONE}"
  printf '\n'
} >> "$LOG_FILE"

LOG_PANE=$(log_pane || true)
if [[ -n "$LOG_PANE" ]]; then
  note "process-log pane already live: $LOG_PANE (log re-headed above)"
else
  RESUME=0
  for a in looper arch agy-docs agy-gh; do agent_alive "$a" && RESUME=1; done
  if [[ $RESUME -eq 1 ]]; then
    note "partial herd detected — creating panes only for agents that are absent"
    [[ -z "${LOOPER_PANE:-}" ]] && ! agent_alive looper && LOOPER_PANE=$(resume_pane) || true
    [[ -z "${ARCH_PANE:-}"    ]] && ! agent_alive arch    && ARCH_PANE=$(resume_pane)    || true
    [[ -z "${DOCS_PANE:-}"    ]] && ! agent_alive agy-docs && DOCS_PANE=$(resume_pane)   || true
    [[ -z "${GH_PANE:-}"      ]] && ! agent_alive agy-gh   && GH_PANE=$(resume_pane)     || true
    LOG_PANE=$(split_pane "$HERDR_PANE_ID" right) || { warn "log pane split failed"; LOG_PANE=""; }
  else
    DIR_MAIN=right; DIR_STACK=down
    if ! confirm "agents column ${DIR_MAIN} of this pane, services ${DIR_STACK}?"; then
      DIR_MAIN=down; DIR_STACK=right
    fi
    LOOPER_PANE=$(split_pane "$HERDR_PANE_ID" "$DIR_MAIN") || { warn "pane split failed"; exit 1; }
    ARCH_PANE=$(split_pane "$LOOPER_PANE" "$DIR_STACK")    || { warn "pane split failed"; exit 1; }
    DOCS_PANE=$(split_pane "$ARCH_PANE" "$DIR_STACK")      || { warn "pane split failed"; exit 1; }
    GH_PANE=$(split_pane  "$DOCS_PANE" "$DIR_STACK")       || { warn "pane split failed"; exit 1; }
    SRV_PANE=$(split_pane "$HERDR_PANE_ID" "$DIR_STACK")   || { warn "pane split failed"; exit 1; }
    LOG_PANE=$(split_pane "$SRV_PANE" "$DIR_MAIN")         || { warn "log pane split failed"; LOG_PANE=""; }
    note "panes: looper=$LOOPER_PANE arch=$ARCH_PANE agy-docs=$DOCS_PANE agy-gh=$GH_PANE srv=$SRV_PANE log=$LOG_PANE"
  fi
fi
if [[ -n "$LOG_PANE" ]]; then
  herdr pane run "$LOG_PANE" "clear && tail -n 40 -f $LOG_FILE" >/dev/null 2>&1 \
    || warn "could not start the tail — run in pane $LOG_PANE: tail -n 40 -f $LOG_FILE"
  note "process log streams to pane $LOG_PANE"
fi
pause

# ── Stage 6/8 · Seat the agents + standing briefs ─────────────────────────
stage "Seat the agents + standing briefs"
if agent_alive looper; then
  note "looper already live — skipping"
else
  say "starting looper (${AGY_KIND}) in its own pane — it becomes the main pane"
  if ! seat_agent looper "${LOOPER_PANE:?}" AGY_KIND; then
    warn "looper not seated — inspect: herdr agent read looper"
    pause "settle it, then continue (Ctrl-C to abort)"
  fi
fi
if agent_alive arch; then
  note "arch already live — skipping"
else
  say "starting architect: arch (${ARCH_KIND}, ${ARCH_MODEL})"
  if ! seat_agent arch "${ARCH_PANE:?}" ARCH_KIND --model "$ARCH_MODEL"; then
    warn "arch not seated — inspect: herdr agent read arch  ·  herdr agent get arch"
    pause "settle it, then continue (Ctrl-C to abort)"
  fi
fi
if agent_alive agy-docs; then
  note "agy-docs already live — skipping"
else
  seat_agent agy-docs "${DOCS_PANE:?}" AGY_KIND || { warn "agy-docs not seated — inspect: herdr agent read agy-docs"; pause; }
fi
if agent_alive agy-gh; then
  note "agy-gh already live — skipping"
else
  seat_agent agy-gh "${GH_PANE:?}" AGY_KIND || { warn "agy-gh not seated — inspect: herdr agent read agy-gh"; pause; }
fi
for a in looper arch agy-docs agy-gh; do
  herdr agent wait "$a" --timeout 60000 >/dev/null 2>&1 \
    || warn "$a still settling — check: herdr agent get $a"
done
say "seating standing briefs (one-time context; task prompts stay short from here)"
seat_brief looper   "$BRIEFS/looper.md"
seat_brief arch     "$BRIEFS/arch.md"
seat_brief agy-docs "$BRIEFS/worker-docs.md"
seat_brief agy-gh   "$BRIEFS/worker-gh.md"
note "herd: looper (main) · arch (architect) · agy-docs (docs) · agy-gh (github)"
pause

# ── Stage 7/8 · Services ──────────────────────────────────────────────────
stage "Services: kultivait serve on :4114"
if curl -sf --max-time 3 http://localhost:4114/v1/models >/dev/null 2>&1; then
  note "proxy already serving on :4114"
else
  ask SERVE_MATCH "Substring serve prints when ready:"
  [[ -z "${SERVE_MATCH:-}" ]] && SERVE_MATCH="4114"
  write_env SERVE_MATCH "$SERVE_MATCH"
  if [[ -z "${SRV_PANE:-}" ]]; then
    SRV_PANE=$(split_pane "$HERDR_PANE_ID" down) || { warn "pane split failed"; exit 1; }
    note "created a fresh serve pane: $SRV_PANE"
  fi
  herdr pane run "$SRV_PANE" "uv run kultivait serve"
  if ! herdr pane wait-output "$SRV_PANE" --match "$SERVE_MATCH" --timeout 600000; then
    warn "no '${SERVE_MATCH}' seen yet — inspect: herdr pane read $SRV_PANE"
  fi
  if curl -sf --max-time 3 http://localhost:4114/v1/models >/dev/null 2>&1; then
    note "proxy healthy"
  else
    warn "proxy not answering on :4114 yet — arch can still plan; fix before delegating"
  fi
fi
pause

# ── Stage 8/8 · Kickoff by mode ───────────────────────────────────────────
stage "Kickoff: ${MODE}"
case "$MODE" in
  w)
    say "charting pass: arch runs wayfinder-charter with you, LIVE in its pane"
    herdr agent focus arch >/dev/null 2>&1 || true
    if herdr agent prompt arch "$(cat "$BRIEFS/wayfinder-charter.md")

MILESTONE: ${MILESTONE}" >/dev/null 2>&1; then
      note "arch is grilling — focus moved to arch's pane; answer it there"
    else
      warn "could not prompt arch — paste this into its pane:"
      say "herdr agent prompt arch \"\$(cat $BRIEFS/wayfinder-charter.md) + MILESTONE: ${MILESTONE}\""
    fi
    pause "chart the map with arch (destination → tickets), then come back"
    ask MAP_NUM "Map issue number arch created (Enter = skip the auto-kick):"
    if [[ -n "${MAP_NUM:-}" ]]; then
      kick_looper "KICKOFF: Work Wayfinder Map #${MAP_NUM} on ${REPO} per your seat brief — drain the frontier in map order until the map closes, then run milestone closeout (log sync + harvest) and report in your pane. The human is watching."
    else
      SKIPPED+=("looper kickoff — paste it when ready (see lines below)")
    fi
    ;;
  b)
    say "brainstorm pass: arch runs direction → design → PRD → tickets with you, LIVE"
    herdr agent focus arch >/dev/null 2>&1 || true
    if herdr agent prompt arch "$(cat "$BRIEFS/brainstorm.md")

TOPIC: ${MILESTONE}" >/dev/null 2>&1; then
      note "arch is grilling — focus moved to arch's pane; drive the interview there"
    else
      warn "could not prompt arch — paste this into its pane:"
      say "herdr agent prompt arch \"\$(cat $BRIEFS/brainstorm.md) + TOPIC: ${MILESTONE}\""
    fi
    pause "finish the interview (spec + tickets published), then come back"
    if confirm "kick the looper to drain the new tickets now?"; then
      kick_looper "KICKOFF: Drain the freshly published brainstorm tickets on ${REPO} per your seat brief — no map this time; a flat queue. Same loop: claim → dispatch arch → verify → retire → log. Stop and report when the queue is dry."
    fi
    ;;
  r)
    kick_looper "KICKOFF: Work Wayfinder Map #${MAP_NUM} on ${REPO} per your seat brief — drain the frontier in map order until the map closes, then run milestone closeout (log sync + harvest) and report in your pane. The human is watching."
    ;;
  s)
    note "seat-only: the herd is idle and briefed; kick it whenever with either line:"
    say "herdr agent prompt looper \"KICKOFF: Work Wayfinder Map #N on ${REPO} per your seat brief — drain the frontier, then closeout, then report.\""
    say "herdr agent prompt arch \"\$(cat $BRIEFS/wayfinder-charter.md) + MILESTONE: <one-liner>\""
    ;;
esac

finish
note "usage:   scripts/herdr-kultivait-session.sh          (any mode; finished stages skip)"
note "briefs:  scripts/herdr-briefs/*.md                  (edit these, not the library)"
note "watch:   looper pane = main · log pane = /tmp/herdr-process.log · serve = :4114"
